"""add_exchange_rates_table

Revision ID: 04858647df73
Revises: dddd1a865df7
Create Date: 2026-01-16 20:32:35.621029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04858647df73'
down_revision: Union[str, Sequence[str], None] = 'dddd1a865df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_created_at'), 'exchange_rates', ['created_at'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_created_at'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
