"""Base version

Revision ID: dddd1a865df7
Revises: 
Create Date: 2026-01-15 16:31:10.052770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dddd1a865df7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('SUBSCRIPTION_CREATED', 'SUBSCRIPTION_PAUSED', 'SUBSCRIPTION_RESUMED', 'SUBSCRIPTION_CANCELLED', 'SUBSCRIPTION_REACTIVATED', 'TIER_SUBSCRIBED', 'TIER_RENEWED', 'TIER_EXPIRED', 'TIER_UPGRADED', 'PAYMENT_INITIATED', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'PAYMENT_REFUNDED', 'TRADE_COPIED', 'TRADE_EXECUTED', 'TRADE_FAILED', 'USER_REGISTERED', 'USER_VERIFIED', 'USER_API_KEY_ADDED', 'USER_API_KEY_REMOVED', name='event_type_enum'), nullable=False),
    sa.Column('aggregate_type', sa.Enum('SUBSCRIPTION', 'TIER_ACCOUNT', 'PAYMENT', 'TRADE', 'USER', 'TRADER_PROFILE', name='aggregate_type_enum'), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_events_aggregate', 'domain_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index(op.f('ix_domain_events_aggregate_id'), 'domain_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_domain_events_created_at'), 'domain_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_events_event_type'), 'domain_events', ['event_type'], unique=False)
    op.create_index('ix_domain_events_type_time', 'domain_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_domain_events_user_id'), 'domain_events', ['user_id'], unique=False)
    op.create_index('ix_domain_events_user_time', 'domain_events', ['user_id', 'created_at'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRADE_PROFIT', 'PERFORMANCE_FEE', 'SUBSCRIPTION_FEE', 'VIRTUAL_ISSUANCE', 'VIRTUAL_RESET', 'VIRTUAL_RESET_FREE', name='transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REVERSED', name='transaction_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('tx_metadata', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_external_reference'), 'ledger_transactions', ['external_reference'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_reference_id'), 'ledger_transactions', ['reference_id'], unique=True)
    op.create_index(op.f('ix_ledger_transactions_type'), 'ledger_transactions', ['type'], unique=False)
    op.create_table('trading_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier_name', sa.Enum('STANDARD', 'PREMIUM', 'FREE', name='subscriptiontier'), nullable=False),
    sa.Column('max_follows', sa.Numeric(), nullable=False),
    sa.Column('monthly_fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PLUS', 'BUSINESS', name='usertier'), nullable=False),
    sa.Column('virtual_balance_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('virtual_balance_blown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('SYSTEM_FEE_WALLET', 'SYSTEM_BANK_SETTLEMENT', 'SYSTEM_BANK_BALANCE', 'USER_LIVE_WALLET', 'USER_DEMO_WALLET', name='account_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_table('exchange_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_exchange', 'exchange_keys', ['user_id', 'exchange_name'], unique=False)
    op.create_index('idx_user_key', 'exchange_keys', ['user_id', 'api_key'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('subscription_tier_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('payment_ref', sa.String(length=255), nullable=True),
    sa.Column('tier_status', sa.Enum('ACTIVE', 'EXPIRED', 'RENEWED', name='subscriptiontierstatus'), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['trading_tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_tier_accounts_user_id'), 'subscription_tier_accounts', ['user_id'], unique=False)
    op.create_table('trader_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('performance_fee_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_allocation_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('min_capital_requirement', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_KYC', 'INCUBATION', 'PROBATION', 'ACTIVE', 'SUSPENDED', name='traderprofilestatus'), nullable=False),
    sa.Column('stats_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('probation_trades_count', sa.Integer(), nullable=True),
    sa.Column('probation_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_roi', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trader_profiles_alias'), 'trader_profiles', ['alias'], unique=True)
    op.create_index(op.f('ix_trader_profiles_is_active'), 'trader_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_trader_profiles_user_id'), 'trader_profiles', ['user_id'], unique=True)
    op.create_table('user_kyc',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id_document_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=True),
    sa.Column('past_trades', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('trader_profile_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('changes', sa.String(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trader_profile_id'], ['trader_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='entry_direction'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leader_profile_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP_LOSS', 'TAKE_PROFIT', name='order_type'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('raw_exchange_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader_profile_id'], ['trader_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_emitted_at'), 'signals', ['emitted_at'], unique=False)
    op.create_index('ix_signals_leader_emitted', 'signals', ['leader_profile_id', 'emitted_at'], unique=False)
    op.create_index(op.f('ix_signals_leader_profile_id'), 'signals', ['leader_profile_id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('trader_id', sa.UUID(), nullable=False),
    sa.Column('tier_account_id', sa.UUID(), nullable=False),
    sa.Column('sub_status', sa.Enum('ACTIVE', 'PAUSED', 'LIQUIDATED', 'INACTIVE', name='subscriptionstatus'), nullable=False),
    sa.Column('copy_mode', sa.Enum('PROPORTIONAL', 'FIXED_AMOUNT', name='copymode'), nullable=False),
    sa.Column('allocation_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_shadow_mode', sa.Boolean(), nullable=False),
    sa.Column('virtual_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_account_id'], ['subscription_tier_accounts.id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['trader_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'trader_id', name='uq_subscriber_trader')
    )
    op.create_index(op.f('ix_subscriptions_subscriber_id'), 'subscriptions', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_trader_id'), 'subscriptions', ['trader_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('exchange_key_id', sa.UUID(), nullable=True),
    sa.Column('binance_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'FAILED', 'PARTIALLY_FILLED', name='trade_status'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side_trade'), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('filled_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fee_paid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fee_currency', sa.String(length=10), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=True, comment='Final PnL snapshot when trade closes'),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_key_id'], ['exchange_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_binance_order_id'), 'trades', ['binance_order_id'], unique=False)
    op.create_index(op.f('ix_trades_signal_id'), 'trades', ['signal_id'], unique=False)
    op.create_index('ix_trades_signal_status', 'trades', ['signal_id', 'status'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index('ix_trades_subscription_created', 'trades', ['subscription_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_trades_subscription_id'), 'trades', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_subscription_id'), table_name='trades')
    op.drop_index('ix_trades_subscription_created', table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index('ix_trades_signal_status', table_name='trades')
    op.drop_index(op.f('ix_trades_signal_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_binance_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_subscriptions_trader_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subscriber_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_leader_profile_id'), table_name='signals')
    op.drop_index('ix_signals_leader_emitted', table_name='signals')
    op.drop_index(op.f('ix_signals_emitted_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('user_kyc')
    op.drop_index(op.f('ix_trader_profiles_user_id'), table_name='trader_profiles')
    op.drop_index(op.f('ix_trader_profiles_is_active'), table_name='trader_profiles')
    op.drop_index(op.f('ix_trader_profiles_alias'), table_name='trader_profiles')
    op.drop_table('trader_profiles')
    op.drop_index(op.f('ix_subscription_tier_accounts_user_id'), table_name='subscription_tier_accounts')
    op.drop_table('subscription_tier_accounts')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_user_key', table_name='exchange_keys')
    op.drop_index('idx_user_exchange', table_name='exchange_keys')
    op.drop_table('exchange_keys')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trading_tiers')
    op.drop_index(op.f('ix_ledger_transactions_type'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_reference_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_external_reference'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index('ix_domain_events_user_time', table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_user_id'), table_name='domain_events')
    op.drop_index('ix_domain_events_type_time', table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_event_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_created_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_aggregate_id'), table_name='domain_events')
    op.drop_index('ix_domain_events_aggregate', table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###
